import { defineStore } from 'pinia';

export const useMoviesStore = defineStore('movies', {
  state: () => ({
    movies: [],
    loading: false,
    error: null,
  }),
  actions: {
    async fetchMovies() {
      // 之後改成呼叫後端 API
      this.loading = true;
      this.error = null;
      try {
        this.movies = [
          {
            id: 1,
            title: '終極戰士：殺戮星球',
            engTitle: 'Predator: Badlands',
            runtimeMinutes: 108,
            genres: '動作，冒險',
            cast: '艾兒芬妮，迪米特里烏斯，科羅馬坦吉',
            director: '丹雀柏格',
            description:'宇宙最強獵人終極戰士身處危機四伏的神秘星球，但這次他並非因爲嗜血而大開殺戒，而竟是被逐出自己的家園，且被迫展開「獵殺訓練」，才能為自己贖回返家的資格！ 本集武器也再度升級，除了終極戰士的招牌「開山刀」，更有強化版弓箭和超帥迴旋鏢，令他的戰鬥力大幅提升，即使面臨再龐大凶猛的飛天遁地駭人怪獸，從掠食者成為獵物的他也無須畏懼並咆哮宣示：「我不是任何人的獵物！」但艾兒芬妮最後又丟出一句：「這趟獵殺我們並不孤單」，要他做好全力迎戰的心理準備…',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/37/3766e55550910020c0d09173e5cc5c53.jpg',
            trailerUrl:'https://www.youtube.com/embed/n-5VckJK3KQ?si=Kk0HYw2qyVMk86ka',
            releaseDate: '2025/11/06',
          },
          {
            id: 2,
            title: '魔法壞女巫：第二部',
            engTitle: 'Wicked: For Good',
            runtimeMinutes: 138,
            genres: '奇幻，劇情',
            cast: '辛西婭艾利沃，亞莉安娜，喬納森貝利，伊森斯萊特，楊伯文，瑪麗莎博德，楊紫瓊，傑夫高布倫',
            director: '朱浩偉',
            description:'本片由第一集《魔法壞女巫》朱浩偉執導，回歸演出的演員包括辛西婭艾利沃及亞莉安娜等，這個關於奧茲國女巫從未敘述的故事，講述自從艾法芭與格琳達分道揚鑣、形同陌路之後，各自承受她們做出的抉擇所帶來的後果。 被冠上“西方壞女巫”惡名的艾法芭（辛西婭艾利沃 飾）遭到放逐後，隱居在奧茲國樹林深處，但是卻仍然為被噤聲的動物爭取自由而奮鬥，並且迫切地想要揭露她所知道關於奧茲國大巫師（傑夫高布倫 飾）的真相。 與此同時，格琳達已經成為奧茲國光鮮亮麗的良善象徵，她住在翡翠城皇宮中，享受她的響亮名聲和超高人氣所帶來的明星光環與特權。在莫里貝爾夫人（奧斯卡獎得主楊紫瓊 飾）的安排下，格琳達成為奧茲國人民眼中充滿粉紅泡泡的安撫力量，並且讓他們相信奧茲國在大巫師的統治之下一切都很好。 當格琳達的明星光環越來越閃亮，她也準備和費耶羅王子（奧立佛獎得主、艾美獎及演員工會獎提名喬納森貝利 飾）舉行一場盛大的婚禮，但是她卻一直受到她和艾法芭分開後的陰影所糾纏。她試圖促成艾法芭與大巫師之間的和解，然而她所有的努力都以失敗告終，使得艾法芭和格琳達的關係越來越疏遠。她們的關係決裂所造成的影響，將徹底改變博克（東尼獎入圍者伊森斯萊特 飾）與費耶羅的命運，也將威脅到艾法芭的妹妹涅莎蘿絲（瑪麗莎博德 飾）的安危，而一名來自堪薩斯州的少女也將闖入奧茲國，徹底翻轉他們的世界。 當一群憤怒的民眾揭竿而起，打算對抗西方壞女巫，格琳達和艾法芭就必須最後一次攜手合作。當她們的友情成為改變她們未來的關鍵，她們就必須以真心誠意和無比的同理心真正了解彼此，並且改變自己，也讓整個奧茲國變得更美好。',
            ratingLevel: '/images/ic_rating_pg12.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/32/320e7dac80e2ac7dae7b0147285b5e03.jpg',
            trailerUrl:'https://www.youtube.com/embed/M4oZYkUd0Kc?si=6cO-2odIveqRTRou',
            releaseDate: '2025/11/19',
          },
          {
            id: 3,
            title: '逃亡遊戲',
            engTitle: 'The Running Man',
            runtimeMinutes: 132,
            genres: '動作，冒險，驚悚',
            cast: '格倫鮑威爾，威廉麥斯，李佩斯，艾美莉亞鍾斯，米高施拿，丹尼爾伊薩，潔美羅森，高文杜明高，佐舒布連',
            director: '艾加韋特',
            description:'在不久後的將來，「逃亡遊戲」是社會上收視率最高的電視節目。這是一場致命競賽，參賽者被稱為「逃亡者」。在賽事進行的30天內，他們不斷地被職業殺手追殺；而整個逃生過程，逃亡者及殺手的一舉一動，都會實時直播，讓嗜血的觀眾收看。參賽者每生存一天，獎金就會增加；活著完成賽事，即可獲得天價巨獎。本是普通打工仔的賓查理斯（格倫鮑威爾），為了應付女兒的巨額醫療開支，被表面親和力強但實質冷血殘酷的節目監製丹基里安（佐舒布連）說服參賽。憑著反抗本能、敏銳直覺及過人身手，賓查理斯贏得海量粉絲的支持，同時亦成為了整個社會制度的威脅。隨著節目的收視率飆升，危機也隨之倍增。賓查理斯不僅要戰勝殺手，還要戰勝無數想看著他被獵殺的市民。',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/82/82db62467cc92d25fd1853f87d92a280.jpg',
            trailerUrl:'https://www.youtube.com/embed/7Z7U_LVf2vI?si=pjXqpH7a850cBrgo',
            releaseDate: '2025/11/12',
          },
          {
            id: 4,
            title: '暴蜂尼亞',
            engTitle: "BUGONIA",
            runtimeMinutes: 118,
            genres: '驚悚',
            cast: '艾瑪史東、傑西普萊蒙、艾力戴軍比利、史塔洛斯奧雷亞斯',
            director: '尤格藍西莫',
            description:'劇情顛覆想像，【暴蜂尼亞】講述兩名懷有陰謀論的年輕男子，突發奇想綁架了一位位高權重、冷酷無情的女執行長蜜雪兒，因為他們深信她其實是企圖摧毀地球的外星人。兩人把她鎖在地下室，與她正面對質時，雙方很快地陷入一場始料未及、難以預測的戰鬥。 【暴蜂尼亞】由演技派巨星傑西普萊蒙和艾瑪史東攜手新進演員艾丹戴爾比斯共同詮釋威爾崔西精彩犀利的劇本，導演尤格藍西莫以大膽新穎的手法，描繪人類面對命運時的歡笑、淚水和畏懼。',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/66/665ad49c39fb48efb9ea13e7e2fac18a.jpg',
            trailerUrl:'https://www.youtube.com/watch?v=ru0eMlDMRSc',
            releaseDate: '2025/11/07',
          },
          {
            id: 5,
            title: '劇場版『鏈鋸人 蕾潔篇』',
            engTitle: "Chainsaw Man – The Movie: Reze Arc",
            runtimeMinutes: 100,
            genres: '動畫，動作',
            cast: '<CV>戶谷菊之介，井澤詩織，楠木燈，坂田將吾，菲魯茲藍，高橋花林，花江夏樹，內田夕夜，內田真禮，上田麗奈',
            director: '吉原達矢',
            description:'《鏈鋸人動畫版》動作導演吉原達矢執導，《劇場版 咒術迴戰 0》《膽大黨動畫版》瀨古浩司編劇，《鏈鋸人動畫版》戶谷菊之介配音，鏈鋸人首度登上大銀幕，帶來一場火力全開的動作冒險，延續這部動畫系列的篇章。 為了償還父母留下的債務，為黑道打工的惡魔獵人淀治，遭到背叛並慘遭殺害。在意識消散之際，與他感情深厚的鏈鋸惡魔狗波奇塔，與淀治簽訂契約救了他一命，也讓兩人合而為一，從此誕生了所向無敵的「鏈鋸人」。 如今，在惡魔、獵人與潛藏敵人交鋒的殘酷戰爭中，一位神秘少女蕾潔，闖入了淀治的世界。面對史上最致命的對決，淀治將在這個毫無規則可言的生存遊戲中，被愛推向命運的漩渦。',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/84/840ee28b85246ddb4b01dbbfb755db1e.jpg',
            trailerUrl:'https://www.youtube.com/embed/ttUwLaUr-a0?si=yrqzo-YqWVz9d6Wq',
            releaseDate: '2025/09/24',
          },
          {
            id: 6,
            title: '國寶',
            engTitle: "Kokuho",
            runtimeMinutes: 175,
            genres: '劇情',
            cast: '吉澤亮，橫濱流星，高畑充希，寺島忍，森七菜，三浦貴大，見上愛，黑川想矢，越山敬達，永瀨正敏，嶋田久作，宮澤艾瑪，中村鴈治郎，田中泯，渡邊謙',
            director: '李相日',
            description:'改編自作家吉田修一生涯代表作，講述出身黑道家庭、擁有盛世美顏的喜久雄（吉澤亮 飾），在失去父親後，被歌舞伎名門花井半二郎（渡邊謙 飾）收留，意外踏入歌舞伎的世界。天賦異稟的喜久雄與花井家繼承人俊介（橫濱流星 飾）成為好友，成長經歷與才能都不同的兩人互相競爭成長，將青春奉獻給舞台。為了爬上歌舞伎的頂端，命運的抉擇與人生轉折讓他們兩人的未來走向截然不同的道路..',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/3b/3b6f7ebe508ade8bc9200ce39e9b4868.jpg',
            trailerUrl:'https://www.youtube.com/embed/qnqsxKY37-s?si=2LfQwdf_mVuqInG5',
            releaseDate: '2025/10/23',
          },
          {
            id: 7,
            title: '泥娃娃',
            engTitle: "Mudborn",
            runtimeMinutes: 111,
            genres: '恐怖，驚悚',
            cast: '楊祐寧，蔡思韵，張軒睿，郭雪芙，周采詩',
            director: '解孟儒',
            description:'童謠的背後，隱藏著神秘驚悚的故事。在遊戲公司工作的旭川（楊祐寧 飾），為開發一項新的恐怖VR遊戲，意外將一尊來自凶宅現場的殘破泥娃娃帶回家，沒想到懷有身孕、身為文物修護師的妻子慕華（蔡思韵 飾）對其產生異常執念，不斷進行修復。隨著家中怪事頻傳，慕華狀態也越來越虛弱，旭川無計可施，輾轉求助通靈驅魔人阿生（張軒睿 飾），而泥娃娃背後深埋的駭人祕密，也隨之浮出水面⋯',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/22/2283c0b98dbbc55f9880cbd7f2609794.jpg',
            trailerUrl:'https://www.youtube.com/embed/LHqXG25pFL8?si=Xdwc7jyT3cDqag5a',
            releaseDate: '2025/10/09',
          },
          {
            id: 8,
            title: '劇場版「鬼滅之刃」無限城篇 第一章 猗窩座再襲',
            engTitle: "Demon Slayer：Kimetsu no Yaiba Infinity Castle",
            runtimeMinutes: 154,
            genres: '動畫，奇幻',
            cast: '花江夏樹，櫻井孝宏，下野紘，松岡禎丞',
            director: '外崎春雄',
            description:'竈門炭治郎為了讓成為鬼的妹妹禰豆子變回人類，加入狩獵鬼的組織「鬼殺隊」。入隊之後，他與夥伴我妻善逸以及嘴平伊之助跟各式各樣的鬼戰鬥，在成長的同時加深友情與羈絆。然後，炭治郎與「鬼殺隊」最高階的劍士「柱」一同戰鬥，在《無限列車》跟炎柱煉獄杏壽郎、在《遊郭》跟音柱宇髓天元、在《刀匠村》則是跟霞柱時透無一郎以及戀柱甘露寺蜜璃一起展開激烈的戰鬥。 其後，為了面對與鬼即將到來的決戰，隊員們集體參加「柱」所舉行的聯合強化訓練《柱訓練》。此時，鬼舞辻無慘卻出現在「鬼殺隊」的大本營產屋敷府。雖然「柱」們與炭治郎連忙趕去營救陷入危機的主公大人，卻在無慘的操縱之下落入了充滿謎團的空間。炭治郎等人落下的地方，正是鬼的大本營「無限城」── 「鬼殺隊」與「鬼」的最終決戰，序幕就此揭開。',
            ratingLevel: '/images/ic_rating_pg12.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/51/517af03926e178d1ae5c2ce0e261acde.jpg',
            trailerUrl:'https://www.youtube.com/embed/BVewQAMqLbw?si=uyEOgyMJKa593hgL',
            releaseDate: '2025/08/08',
          },
          {
            id: 9,
            title: '蟲',
            engTitle: "LOCUST",
            runtimeMinutes: 135,
            genres: '劇情',
            cast: '劉韋辰，潘綱大，游安順，李夢苡樺，吳奕蓉，馬念先',
            director: '王凱民',
            description:'2019年的台灣適逢燥熱大選，一場抗爭也在香港發生。小人物的生活還在繼續，失語年輕人鍾翰在台北親戚家的傳統小吃店寄人籬下，雖被真心相待，卻難解內心虛渺。他在每個暗夜投奔幫派，縱情舞池，既在超商邂逅戀曲，卻也一步步陷入政商黑土地權謀的腥風血雨，直至終於無法抽身。台裔編導王凱民聯合多國合製，對照政治動盪與常民日常，捕捉緊繃氛圍下的台北暗流。',
            ratingLevel: '/images/ic_rating_pg15.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/df/dfa151144e0fd27d5aa000844495205f.7',
            trailerUrl:'https://www.youtube.com/embed/vvaBzoG7ISs?si=3NvemVxQ5RGo-eUv',
            releaseDate: '2025/11/07',
          },
          {
            id: 10,
            title: '未完的情歌',
            engTitle: "LOVE SONG",
            runtimeMinutes: 120,
            genres: '愛情',
            cast: '森崎溫，向井康二（Snow Man）',
            director: '維拉奇．通吉拉',
            description:'人氣BL泰劇《只因我們天生一對》導演大銀幕操刀日泰合製話題新作，邀來《一級玩家》日籍緬甸人氣演員森崎溫，和偶像團體Snow Man日泰混血成員向井康二攜手演繹青梅竹馬，輾轉東京和曼谷，橫跨曖昧揪心的悸動與期盼，共譜一段純真的雙向愛戀。總是過分正經、有著嚴謹潔癖的靦腆研究員壯太從未交過女友，某日突然接到外派泰國的工作機會。本來興趣缺缺，卻在得知學生時期的暗戀對象也在曼谷那刻，決定邁出勇敢一步。攝影師小海是校園中的風雲男孩，總在天臺彈著吉他，卻在某日不告而別，成了壯太心中永遠的謎。睽違六年的命定重逢、悸動依舊，但苦戀的痛楚卻將壯太一點點吞噬，那首「未完的情歌」承載著他們之間的密語，還有小海道不出口的真心……',
            ratingLevel: '/images/ic_rating_p.png',
            posterUrl: 'https://capi.showtimes.com.tw/assets/46/46ad2ae1f17d2428b1ad9cda466967be.jpg',
            trailerUrl:'https://www.youtube.com/embed/eT7tOJK50Is?si=hsZ22A-OIYalZwB-',
            releaseDate: '2025/11/07',
          },
          
        ];
      } catch (err) {
        this.error = '載入電影列表失敗';
      } finally {
        this.loading = false;
      }
    },

    getMovieById(id) {
      return this.movies.find((m) => String(m.id) === String(id)) || null;
    },
  },
});
